
**** TODO Obs! dette dokumentet er ikke sjekket for skrivefeil!

* Introduksjon
  Gratulerer med beslutningen om å dra til Japan! Det vil du ikke angre på!
  Jeg håper dette dokumentet kan hjelpe deg å få en oversikt over hva som 
  må på plass av dokumentasjon og papirer før du kan reise. 

  Det vil også inneholde noe informasjon om hva du må ordne når du ankommer, 
  og litt generelle tips og erfaringer fra en student til en annen :)
* Praktisk info
** Dokumenter / søknader
   Etter at din veileder har kontaktet Universitetet i Kyushu og det har 
   blitt klart at du kan reise, vil du få en mail fra Universitetet. I denne
   mailen vil fremgangsmåten i prosessen bli forklart, og du vil få 
   søknadsskjemaet "KYUSHU UNIVERSITY SPECIAL RESEARCH STUDENT APPLICATION 
   FORM". Fyll ut dette etter beste evne, med HAKER der du skal markere 
   alternativer. (Kryss blir vanligvis brukt for å kansellere, dersom du har 
   markert feil alternativ.) 

   Sammen med søknadsskjemaet vil du bli bedt om å sende en del andre 
   dokumenter. (Nederst på søknaden står hvilke) 

   Nedenfor er en forklaring for noen av dem, og andre papirer du vil trenge.
   
   | Dokumenter og ting du kan ordne med en gang | Får tilsendt                                | Siste steg |
   |---------------------------------------------+---------------------------------------------+------------|
   | Student Registration Certificate            | Certificate of Eligibility                  | Visum      |
   | Academic transcript                         | Kyushu special research student application |            |
   | Passfoto                                    | Research plan                               |            |
   |                                             |                                             |            |
   | Letter of recommendation                    |                                             |            |
   | Certificate of scholarship                  |                                             |            |
   |                                             |                                             |            |
   | Bank statement                              |                                             |            |
   |---------------------------------------------+---------------------------------------------+------------|
   | Vaksiner                                    |                                             |            |

*** Notater for et par punkter i søknadsskjemaet
    I punkt 3 blir du bedt om å fylle ut navnet ditt i katakana, hvis du vet
    hvordan. Dersom du ønsker å fylle ut dette kan et godt tips være å finne 
    wikipedia-siden til en person med samme navn som deg, og skifte språk til
    Japansk. 

    I tabellen for "Academic Data" skal du ikke fylle ut ditt nåværende 
    studieprogram i tabellen med resten av Utdanningen. Det er et eget felt 
    for det under.

    Under punktet "Financial support" vil du huke av for "Scolarship except 
    Japan". "Sponsor's name" vil være "Norwegian Research Council/University 
    of Oslo" dersom du deltar i COINMAC samarbeidet.
    Du trenger ikke å fylle ut noe mer enn dette under "Financial support".
*** Research plan
    Dette er også et dokument du vil få når du først kommer i kontakt med 
    Universitetet. Ganske enkelt kan du beskrive hva masteroppgaven din 
    går ut på. Hvis du må ta fag mens du er i Japan tenker jeg dette også 
    er relevant å skrive i dette dokumentet.
*** Passfoto
    Du vil trenge et passfoto som er tatt for ikke lenger enn 6 måneder siden.
    Print gjerne ut 5-6 stykker da du vil få bruk for dem til studentkort o.l.
*** Student registration certificate
    Her kan du be studieadministrasjonen om et brev som bekrefter at du er
    tatt opp som student ved Universitetet i Oslo i perioden utvekslingen 
    finner sted.
*** Letter of Recommendation
    Før du søker kan det være greit å ha klart et anbefalingsbrev fra din
    veileder, da du trenger dette senere i søknadsprosessen.
*** Certificate of Eligibility
    Du vil få dette etter at søknadsprosessen til universitetet et ferdig.
    Dette dokumentet er det viktig å komme i gang med å skaffe tidlig, da
    det kan ta lang tid å få det utsendt. I mitt tilfelle tok det 2-3 måneder
    før dokumentet var klart. Deretter må det også være nok tid til at du 
    får dokumentet tilsendt. Dette kan ta minst 2 uker.
*** Academic Transcript
    Her holder det med en engelsk utskrift av karakterene dine fra 
    Universitetet, eventuelt fra tidligere studier. Det er mest viktig å få 
    med det siste du har gjort.
*** Penger
    De ønsker at du skal bevise at du kan klare deg den tiden du er i Japan.
    Derfor må du gjøre klar følgende dokumenter.
**** Bank statement
     Her holder det med en kontoutskrift der det går frem hvor mye du har som
     utgående saldo.

     Dersom du bare kan få denne på norsk fra din bank må du selv legge ved en 
     oversettelse til engelsk.
**** Certificate of Scolarship
     Dette dokumentet skal være en bekreftelse på stipendet du får under 
     oppholdet. i.e. en bekreftelse på hva du får fra COINMAC samarbeidet.
     I tillegg kan du opplyse om lån/stipend du får fra lånekassen.
*** Visum
    Etter at du har fått Certificate of Eligibility tilsendt, kan du søke om
    visum ved den Japanske ambassaden i Oslo. Søknadsprosessen her tar rundt
    1 uke dersom alle papirene er i orden. Man trenger heller ikke å bestille
    time før man drar til ambassaden.
 
    Dersom du likevel har dårlig tid er det mulighet for å få utsendt visum 
    fortere. Hvis alle papirene dine er i orden, og du sender scannet kopi til 
    ambassaden på forhånd, kan man bestille "one day visa issuing". Da kan man 
    komme til ambassaden mellom kl. 09:00 og 10:00 for å levere alle originale 
    papirer. Ambassaden vil da sende ut visum samme dag kl. 15:00.

    [[http://www.mofa.go.jp/files/000124525.pdf][Søknadsskjema]]

    [[http://www.mofa.go.jp/j_info/visit/visa/process/long.html][Flytskjema]]

    Mer info om [[http://www.mofa.go.jp/j_info/visit/visa/long/visa6.html][studentvisum]]

    Hjemmesiden til [[http://www.no.emb-japan.go.jp/itprtop_nb/index.html][Japans ambassade i Norge]]

    Beboere i Norge kan komme til Japan uten å søke om turistvisum før de reiser, 
    du får det når du ankommer immigrasjonen. Du kan da være i Japan i inntil 3 
    måneder på dette visumet før du må reise ut. 

    Hvis du mot all formodning ikke skulle få søkt om visum før du reiser, kan 
    du fortsatt søke om å skifte status fra turistvisum til langtids visum etter 
    at du har ankommet Japan. 
    
    Vær obs på at å skifte fra turistvisum til langtids studentvisum er svært uvanlig,
    og fører til en del ekstra arbeid. Heldigvis fikk jeg hjelp av en på labben som 
    hadde vært gjennom det samme.
** Språkkurs
   Jeg vil absolutt anbefale å bruke tiden før du reiser/den første tiden du er 
   her til å lære litt grunnleggende Japansk. De regner ikke med at du kan noe 
   japansk på labben, men jeg vil si at de daglige gjøremålene blir mye lettere 
   dersom du kan noe grunnleggende. (Kan anbefale "Genki" til selvstudium dersom
   du har tid.)

   Du kan få noe av det du betaler for språkkurs dekket av lånekassen. Du må da 
   være påpasselig med at kurset går over mer enn 4 uker for å kvalifisere. 
   Kyushu arrangerer språkkurs som sammenfaller med sommerferien, men de har 
   ganske tidlig søknadsfrist, og jeg har ikke sjekket hvor lenge dette varer.
   (Jeg tok et annet kurs på Kwansei Gakuin University, men det varte bare i 
   3 uker.)
** Helse
   OBS! Dette dokumentet er ikke skrevet av kvalifisert helsepersonell, 
   og er kun ment til orientering for at du skal kunne planlegge tiden 
   du må bruke før du reiser. Derfor må du selv sjekke faktaopplysninger 
   og snakke med legen din angående vaksiner osv.

   Les gjerne mer om dette for oppdatert informasjon på [[https://www.regjeringen.no/no/tema/utenrikssaker/reiseinformasjon/velg-land/reiseinfo_japan/id2415973/][ud's hjemmesider]].
*** Vaksiner
    Oppdatert informasjon om vaksiner finner du hos [[https://www.fhi.no/sv/vaksine/reisevaksiner/verden/vaksiner-ved-reise-til-asia/][fokehelseinstituttet]].
    Du vil måtte ta vaksinene for gruppe II. Dersom du ikke har fått 
    påfyll av barnevaksinene bør du få påfyll av disse også, da det er anbefalt
    å ta dem rundt hvert tiende år. (disse er dTP-IPV og muligens TBE.)

    Du kan sjekke hvilke vaksiner du har tatt og når du tok dem hos [[https://helsenorge.no/vaksiner/mine-vaksiner][mine vaksiner]]. 
    Ta med en utskrift av dette når du går til legen.

    Videre er de nye vaksinene du eventuelt trenger Japansk encefalitt og 
    Hepatitt-B vaksine. Disse kan du bestille hos [[https://www.sio.no/helse/reisevaksine][SiO's reisevaksinasjon]]. 
    Japansk encefalittvaksinen må tas i 2 doser med ca 28 dagers mellomrom.
    (Den kan visstnok tas med 7 dagers mellomrom, men legen anbefalte å vente
    de 28 dagene.)

    Prisen som står hos SiO er per dose. 

    Hepatitt-B vaksine gis vanligvis i 4 doser for best beskyttelse, og bør 
    startes tidlig. Dette fordi man vanligvis venter 5 mnd mellom dose 2 og 3. 
    Men, den kan også gis i hurtigregime. Da tar prosessen rundt 1 måned, og 
    du kan ta den 4 dosen når du kommer hjem etter 1 år (dersom du ønsker å 
    en langtidsvirkende vaksine.) se [[https://www.fhi.no/nettpub/vaksinasjonsveilederen/vaksiner-mot-de-enkelte-sykdommene/hepatitt-b-vaksinasjon-og-hepatitt-/][Tabell 4]].
*** Sykdommer som kan forekomme
   Denguefeber - Sykdom spredd av mygg. Jeg fikk opplysning om å beskytte
   meg mot denne sykdommen før jeg reiste. Forebyggende tiltak er rett og 
   slett å unngå å bli stukket av mygg. I skrivende stund har jeg ikke 
   hatt noe særlig problemer med dette. Du kan lese mer om denguefeber på
   [[https://www.fhi.no/nettpub/smittevernveilederen/sykdommer-a-a/denguefeber/][fhi's hjemmesider]].

   Japansk encefalitt - En type hjernehinnebetennelse spredd av mygg. 
   Forebyggende tiltak er vaksinasjon.
** Forsikring
   Dersom du skal være lenger i Japan enn 3 måneder, må du melde deg inn i
   Japans nasjonale helseforsikring. Dette kan du få hjelp ved enten når 
   du søker om visum ved ambassaden i Japan, eller ved helpesenteret når du
   kommer til universitetet. 

   Det er også anbefalt å melde seg inn i ansa, eller en lignende organisasjon,
   og kjøpe deres [[http://www.ansa.no/Forsikring/][studentforsikring]].
    
* Ved ankomst

* Om campus
    
* Annet / kjekt å vite

** [[https://en.wikipedia.org/wiki/Katakana][Katakana]]
   Katakana er ett av de 3 skriftsystemene man bruker i Japan. Det blir 
   vanligvis brukt for å skrive engelske (og bla. portugisiske) lånord og 
   utenlandske navn. I likhet med Hiragana betegner hvert tegn i dette 
   skriftystemet en bestemt lyd (nesten stavelse men ikke helt). 

   Det siste skriftsystemet, Kanji, brukes både for å betegne enkelte ord
   og meninger. Det som gjør ting litt vanskelig er at hvert symbol kan uttales 
   på forskjellige måter, og ha litt forskjellig betydning ut ifra sammenhengen.

** Omiyage
   Det er vanlig at du tar med deg en liten gave dersom du har reist et sted.
   Dette er vanligvis noe spiselig, så ta gjerne med noe snacks/godteri 
   fra Norge som studentene/personellet på laben kan smake. 
   (Valget mitt landet på Kvikk Lunsj)

   Men, vær bevisst på at det kan være restriksjoner på hva du kan få lov til å ta
   med inn i landet. 
